### PR TITLE
Update install packagies

### PR DESCRIPTION
**Pull request by hannut91**
Update install packagies for getting started. in `http.listener.ts` file, use `@marblejs/middleware-logger` and `@marblejs/middleware-body` packagies. But there is no guide to install. 
According to the guide there is no guide to make `index.ts`. So you need to change to `server.ts.`

### CODE REVIEW

**Comment by JozefFlakus** [comment]
Resolves issue #7

**Comment by bitsnaps** [comment]
I had to install `npm i @marblejs/core @marblejs/middleware-logger @marblejs/middleware-body rxjs` to get the current example in the docs working, and yet something is still weird, the app is starting then shutdown without any error or warning, shouldn't be running on `127.0.0.1:1337` as expected? here is the full output:
```
λ - 5440 - 2020-05-21 20:44:04 - http [Context] - Registered: "HttpServerClientToken"
λ - 5440 - 2020-05-21 20:44:04 - http [Context] - Registered: "LoggerToken"
λ - 5440 - 2020-05-21 20:44:04 - http [Context] - Registered: "HttpServerEventStreamToken"
λ - 5440 - 2020-05-21 20:44:04 - http [Context] - Registered: "HttpRequestBusToken"
λ - 5440 - 2020-05-21 20:44:04 - http [Router] - Effect mapped: / GET
λ - 5440 - 2020-05-21 20:44:04 - http [Router] - Effect mapped: /(.*) *
```
and here is the `start` command:
```
"start": "ts-node server.ts",
...
```
I've renamed `index.ts` from the doc to `server.ts`.

**Comment by JozefFlakus** [comment]
Could you post here the complete snippet?
Thanks.

**Comment by bitsnaps** [comment]
I've added `hello.effect.ts` (from the doc) to `/hello` route, here is the full code:
https://github.com/bitsnaps/hello-marblejs

**Comment by JozefFlakus** [comment]
You don't call `main` function 😄 

```
const main: IO<void> = async () =>
  await (await server)();

main();
```

**Comment by bitsnaps** [comment]
@JozefFlakus Oops! my bad, I just copy/paste without understanding the quick guide setup:
https://docs.marblejs.com/getting-started/quick-setup
Thanks!

**Pull request merged**
